before:
  hooks:
  - go mod tidy
  - make notice
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -s -w
  mod_timestamp: '{{ .CommitTimestamp }}'
  tags:
  - netgo
archives:
- files:
  - LICENSE
  - README.md
  - NOTICE.md
  format_overrides:
  - goos: windows
    format: zip
release:
  draft: true
signs:
- cmd: cosign
  signature: "${artifact}.sig"
  args: ["sign-blob", "--output=${signature}", "${artifact}"]
  artifacts: all
source:
  enabled: true
