before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -s -w
  mod_timestamp: '{{ .CommitTimestamp }}'
  tags:
  - netgo
archives:
- files:
  - LICENSE
  - README.md
  - NOTICE.md
release:
  draft: true
