name: release
on:
  push:
    tags:
    - '*'
permissions:
  contents: write
  id-token: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
    - name: Install go-license-detector
      run: |
        go install go.elastic.co/go-licence-detector@latest
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: gha-rskey
        aws-region: us-east-1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
