name: release
on:
  push:
    tags:
    - '*'
  pull_request:
permissions:
  contents: write
  id-token: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install go-license-detector
      run: |
        go install go.elastic.co/go-licence-detector@latest
    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.6.0'
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: gha-rskey
        aws-region: us-east-1
    - uses: actions/cache@v3
      id: goboring-cache
      with:
        path: /opt/goboring/
        key: ${{ runner.os }}-goboring-${{ hashFiles('/opt/goboring/go/VERSION') }}
        restore-keys: |
          ${{ runner.os }}-goboring-
    - name: Set up GoBoring
      if: steps.goboring-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /opt/goboring
        cd /opt/goboring
        wget --no-verbose https://go-boringcrypto.storage.googleapis.com/go1.18b7.linux-amd64.tar.gz
        tar -xzvf go1.18b7.linux-amd64.tar.gz
        /opt/goboring/go/bin/go version
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist --snapshot --skip-sign
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COSIGN_EXPERIMENTAL: 1
    - run: |
        aws sts get-caller-identity
        aws s3 cp dist s3://rstudio-platform-public-artifacts/rskey/devel/ --recursive --exclude "*" --include "*.tar.gz"
